theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
interval = 1

[[block]]
block = "weather"
format = "{weather} {temp}C  {humidity}  ({location})"
service = { name = "openweathermap", api_key = "0b440372cffdd59274b4e0e2594c2f86", city_id = "3855104", units = "metric", lang = "sp" }

[[block]]
block = "bluetooth"
mac = "90:7A:58:C6:73:CF"
format = "🎧"
hide_disconnected = true

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%R"

[[block]]
block = "time"
interval = 5
format = "%A %d/%m"
locale = "es_AR"
