theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "bluetooth"
mac = "90:7A:58:C6:73:CF"
format = "🎧"
hide_disconnected = true

[[block]]
block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%R"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m"
