theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%R"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m"
